# Generated by Django 5.0.2 on 2024-05-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                ("id_arquivo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "DOCX"),
                            ("pptx", "PPTX"),
                            ("xlsx", "XLSX"),
                            ("csv", "CSV"),
                            ("xls", "XLS"),
                        ],
                        max_length=6,
                    ),
                ),
                ("data_do_upload", models.DateTimeField(auto_now_add=True)),
                ("arquivo", models.FileField(upload_to="uploads/")),
                ("nome_do_arquivo", models.CharField(default="", max_length=100)),
            ],
            options={
                "db_table": "arquivo",
            },
        ),
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                ("id_conteudo", models.AutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                ("embeddings", models.BinaryField(null=True)),
                (
                    "id_arquivo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_Chatbot.arquivo",
                    ),
                ),
            ],
            options={
                "db_table": "conteudo",
            },
        ),
    ]
